apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: prod-static-ip 
    networking.gke.io/managed-certificates: findsurfschool-cert
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 8081
          - path: /
            pathType: Prefix
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000 
            
