apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: prod-static-ip 
    networking.gke.io/managed-certificates: findsurfschool-cert
spec:
  rules:
    - host: "*.findsurfschool.com"
      http:
        paths:
          - path: "/api"
            pathType: Prefix
            backend:
              service:
                name: server-cluster-ip-service
                port: 
                  number: 8081
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: client-cluster-ip-service
                port: 
                  number: 3000
            
