apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: server-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 10
    healthyThreshold: 3
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /health
    port: 80
